# @package _global_
#
# Usage:
#   python scripts/rsl_rl/play.py --task=G1-Inspire-HOI-Depth-v0 \
#       --config-dir ./configs/depth --config-name play --load_run <RUN_DIR> --checkpoint <model_XXXX.pt>

defaults:
  - train
  - _self_

env:
  scene:
    num_envs: 1

  commands:
    motion:
      motion_files:
        - ./data/test/smalltable_42clip.npz
      rsi: false
